### ISSUE TITLE
flask run 有错误

### ISSUE THREAD

**Issue by tianke0711** [weijiang1994/university-bbs#17]
我参照这个学习，但是开始运行有错误

我运行的时候有错误:

export FLASKAPP=bbs 这里是bbs还是 __init__.py

flask run 

 

flask.cli.NoAppException: While importing "bbs.bbs", an ImportError was raised: Traceback (most recent call last): File "/opt/anaconda3/lib/python3.8/site-packages/flask/cli.py", line 240, in locate_app __import__(module_name) File "/Users/ketian/PycharmProjects/university-bbs/bbs/__init__.py", line 2, in <module> from bbs.blueprint.index import index_bp ModuleNotFoundError: No module named 'bbs.blueprint.index'

能否清楚的说明一下。

**Comment by weijiang1994** [comment]
先按照我这个仓库的代码跑起来，对照着教程看就行了，前提是要有flask基础，没有的话，可以先把flask文档看一遍。

**Comment by tianke0711** [comment]
@weijiang1994  ok
