### ISSUE TITLE
运行失败

### ISSUE THREAD

**Issue by leayoo** [weijiang1994/university-bbs#2]
我按照Readme的流程进行了操作，但是在flash run以后访问localhost地址报错了

**Comment by weijiang1994** [comment]
> 我按照Readme的流程进行了操作，但是在flash run以后访问localhost地址报错了

问问题至少得把错误贴出来吧？

**Comment by leayoo** [comment]
![Snipaste_2021-05-22_14-14-03](https://user-images.githubusercontent.com/49556315/119216769-28c11c00-bac5-11eb-9756-54a83aca0605.png)
不好意思，错误是这样显示的

**Comment by weijiang1994** [comment]
> ![Snipaste_2021-05-22_14-14-03](https://user-images.githubusercontent.com/49556315/119216769-28c11c00-bac5-11eb-9756-54a83aca0605.png)
> 不好意思，错误是这样显示的

这个错误很明显了，你在对应路径下新建目录、文件就可以了。错误已经提示你了，在university-bbs-main目录下没有logs/bbs.log文件。

**Comment by leayoo** [comment]
成功解决了，非常感谢您的帮助

**Comment by weijiang1994** [comment]
> 成功解决了，非常感谢您的帮助

不客气~
