### ISSUE TITLE
你好 请问一下为啥新建帖子后控制台出错，并且在审核中

### ISSUE THREAD

**Issue by lone0x0** [weijiang1994/university-bbs#4]
![截屏2022-02-22 00 16 01](https://user-images.githubusercontent.com/78702504/154993179-a5619e20-eb9c-4c1e-a90c-59d7160be868.png)
![截屏2022-02-22 00 16 18](https://user-images.githubusercontent.com/78702504/154993186-8cd6b3f3-7c5b-46db-a1b7-f7c795612391.png)

**Comment by weijiang1994** [comment]
审核在配置文件`conf/config.yml`文件中`audit`字段改为`False`就不会审核了

这个错误是你的stmp邮箱没有配置好~

**Comment by lone0x0** [comment]
> 审核在配置文件`conf/config.yml`文件中`audit`字段改为`False`就不会审核了
> 
> 这个错误是你的stmp邮箱没有配置好~

ok 感谢
